apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: techhy-ecosystem-stage-debug-vs
  namespace: techhy-ecosystem-stage-debug
  labels:
    app: techhy-ecosystem-stage-debug
    environment: stage-debug
spec:
  hosts:
  - stage.techhyecosystem.build.infra.gyber.org
  gateways:
  - default/techhy-ecosystem-stage-debug-gateway
  http:
  # 1. ACME Challenge - направляем в istio-system
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver.istio-system.svc.cluster.local
        port:
          number: 8089
  # 2. Все остальные запросы - направляем на приложение
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: stage-debug-techhy-ecosystem-stage-debug-service.techhy-ecosystem-stage-debug.svc.cluster.local
        port:
          number: 80
