apiVersion: apps/v1
kind: Deployment
metadata:
  name: techhy-ecosystem-prod-deployment
  namespace: default
  labels:
    app: techhy-ecosystem-prod
    environment: production
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techhy-ecosystem-prod
      environment: production
  template:
    metadata:
      labels:
        app: techhy-ecosystem-prod
        environment: production
        component: frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: techhy-ecosystem-frontend
        image: ghcr.io/gyberexperiment/tech-hy-ecosystem:production-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {} 