# 🚀 TECH HY Ecosystem Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techhy-ecosystem-frontend
  namespace: techhy-ecosystem-staging
  labels:
    app.kubernetes.io/name: techhy-ecosystem
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: tech-hy-ecosystem
    app.kubernetes.io/managed-by: github-actions
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: techhy-ecosystem
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techhy-ecosystem
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: tech-hy-ecosystem
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/health"
    spec:
      containers:
      - name: frontend
        image: ghcr.io/gyberexperiment/tech-hy-ecosystem:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        # Network Configuration
        - name: REACT_APP_BSC_RPC_URL
          value: "https://bsc-dataseed.binance.org/"
        - name: REACT_APP_BSC_CHAIN_ID
          value: "56"
        - name: REACT_APP_ENVIRONMENT
          value: "production"
        - name: REACT_APP_VERSION
          value: "${IMAGE_TAG}"
        
        # Contract Addresses (Production BSC)
        - name: REACT_APP_VC_TOKEN
          value: "0xC88eC091302Eb90e78a4CA361D083330752dfc9A"
        - name: REACT_APP_VG_TOKEN
          value: "0xe87c0Ff36084033FfB56aCf68F2dD5857C65342d"
        - name: REACT_APP_LP_LOCKER
          value: "0x9269baba99cE0388Daf814E351b4d556fA728D32"
        - name: REACT_APP_GOVERNOR
          value: "0x786133467f52813Ce0855023D4723A244524563E"
        - name: REACT_APP_TIMELOCK
          value: "0x06EEB4c972c05BBEbf960Fec99f483dC95768e39"
        - name: REACT_APP_LP_TOKEN
          value: "0xA221093a37396c6301db4B24D55E1C871DF31d13"
        
        # TECH HY Branding
        - name: REACT_APP_BRAND_NAME
          value: "TECH HY Ecosystem"
        - name: REACT_APP_BRAND_URL
          value: "https://techhy.me"
        - name: REACT_APP_SUPPORT_EMAIL
          value: "i@techhy.me"
        
        # Health Check Configuration
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Resource Management
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Security Context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101  # nginx user
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      
      # Pod Security and Scheduling
      securityContext:
        fsGroup: 101
      imagePullSecrets:
        - name: ghcr-login
      restartPolicy: Always
      
      # DNS Configuration
      dnsPolicy: ClusterFirst
      
      # Termination grace period
      terminationGracePeriodSeconds: 30
      
      # Node selection (optional)
      nodeSelector:
        kubernetes.io/os: linux

---
# 🔄 Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techhy-ecosystem-frontend-hpa
  namespace: techhy-ecosystem-staging
  labels:
    app.kubernetes.io/name: techhy-ecosystem
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: tech-hy-ecosystem
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techhy-ecosystem-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60 