/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lockerDaoSol from "./LockerDAO.sol";
export type { lockerDaoSol };
import type * as timelockControllerSol from "./TimelockController.sol";
export type { timelockControllerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { LPLocker } from "./LPLocker";
export type { LPLockerGovernor } from "./LPLockerGovernor";
export type { VCToken } from "./VCToken";
export type { VGToken } from "./VGToken";
export type { VGTokenVotes } from "./VGTokenVotes";
