resources:
  - deployment.yml
  - service.yml
  - istio-gateway.yml
  - istio-virtualservice.yml
  - certificate.yml

namespace: techhy-main-production

commonLabels:
  app: techhy-main-production
  environment: production

# 🚀 Main Production Specific Configuration
namePrefix: main-

images:
  - name: ghcr.io/gyberexperiment/tech-hy-ecosystem
    newTag: main-latest
