apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techhy-stage-tls
  namespace: istio-system
spec:
  secretName: techhy-stage-istio-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - stage.techhyecosystem.build.infra.gyber.org
