/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVGToken,
  IVGTokenInterface,
} from "../../../contracts/interfaces/IVGToken";

const _abi = [
  {
    inputs: [],
    name: "_OWNER_",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVGToken__factory {
  static readonly abi = _abi;
  static createInterface(): IVGTokenInterface {
    return new Interface(_abi) as IVGTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVGToken {
    return new Contract(address, _abi, runner) as unknown as IVGToken;
  }
}
